name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the repository root.
  SOLUTION_FILE_PATH: .
  # Build configuration and platform.
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build x64 Release
        run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.PLATFORM }} ${{ env.SOLUTION_FILE_PATH }}

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuildArtifact
          path: x64/release/RekordBoxSongExporter.zip

